Added file structure for oneConv operations.
Also fixed a bug where error C4430 would inconsistently appear when building the project. The fix required including the stdint.h in allTDefs.h. I'll need to look into how allTDefs.h was accessing stdint.h in the first place, which allowed uint32_t/uint16_t types (typedefs themselves).